/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Manisha
 * Created : 07/21/2016 11:00:37
 */

package moseley013;

import org.junit.*;
import static org.junit.Assert.*;
import moseley013.Common;



public class CommonTest {

	Common common = new Common();
	/**
	 *
	 * @see moseley013.Common#help()
	 */
	@Test
	public void help() {
		common.help();
	}
	/**
	 *
	 * @see moseley013.Common#helptry()
	 */
	@Test
	public void helptry() {
		common.helptry();
	}

	
}
