/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Manisha
 * Created : 07/19/2016 03:37:07
 */

package moseley013;

import org.junit.*;
import static org.junit.Assert.*;
import moseley013.Guess;



public class GuessTest {

	Guess guess = new Guess();
	/**
	 *
	 * @see moseley013.Guess#collateGuessGrid()
	 */
	@Test
	public void collateGuessGrid() {
		guess.collateGuessGrid();
	}

	
}
